spring:
  datasource:
    url: jdbc:postgresql://138.124.35.157:5432/micro-db
    username: some
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  security:
    user:
      name: some
      password: 123
      roles: admin

  flyway:
    enabled: true
    baseline-on-migrate: true
    table: flyway_schema_history


logging:
  console:
    enabled: true
  file:
    name: logs/app.log
  level:
    root: info
    web: info
    security: info
    SQL: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) [%X{traceId}] %clr(%logger{36}){cyan} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger{36} - %msg%n"

security:
  jwt:
    secret_key: ${JWT_SECRET}
    access_token_expiration: 36000000 # 10 hours
    refresh_token_expiration: 252000000 # 7 days

