-- Таблица пользователей
CREATE TABLE users
(
    id       UUID         NOT NULL DEFAULT gen_random_uuid(),
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_username UNIQUE (username)
);

-- Таблица заказов
CREATE TABLE orders
(
    id          UUID         NOT NULL DEFAULT gen_random_uuid(),
    user_id     UUID         NOT NULL,
    description VARCHAR(500),
    status      VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Таблица токенов
CREATE TABLE tokens
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    access_token  VARCHAR(255),
    refresh_token VARCHAR(255),
    is_logged_out BOOLEAN DEFAULT FALSE,
    user_id       UUID,
    CONSTRAINT pk_tokens PRIMARY KEY (id),
    CONSTRAINT FK_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id)
);